version: "3.4"
volumes: 
  ark:
services:
  init: 
    container_name: init
    image: alpine:latest
    command: 
    - /bin/sh 
    - -c 
    - |
      mkdir -p /ark/server/ShooterGame/Saved/Config/LinuxServer/
      cd /conf
      cp GameUserSettings.ini /ark/server/ShooterGame/Saved/Config/LinuxServer/
      cp Game.ini /ark/server/ShooterGame/Saved/Config/LinuxServer/
      #sleep 900s
    volumes:
    - ark:/ark
    - ./docs/docker/configs/:/conf
  ark:
    container_name: ark
    image: aimvector/ark-server-tools:0.2.3
    environment:
    - SERVERPASSWORD=test
    - ADMINPASSWORD=testadmin
    - BACKUPONSTART=0
    - BACKUPONSTOP=0
    - WARNONSTOP=0
    - UPDATEONSTART=0
    - CLUSTER_ID=thatdevopslocalcluster
    volumes:
    - ./docs/docker/configs/arkmanager/:/etc/arkmanager/
    - ark:/ark
    ports:
    #map 1 aberration
    - 30777:30777/udp 
    - 30778:30778/udp
    - 30777:30777/tcp 
    - 30778:30778/tcp
    - 30015:30015/udp
    - 30016:30016/udp
    #map 2 fjordur
    - 30779:30779/udp 
    - 30780:30780/udp
    - 30779:30779/tcp 
    - 30780:30780/tcp
    - 30018:30018/udp
    - 30019:30019/udp